#!/usr/bin/env bash
# Note: Do not rename this script to "server" because
# it will conflict with 'ember serve' startup processing.

BOTTOM=$(grep BOTTOM .env | cut -d '=' -f2 | cut -d '#' -f1)
echo

if [ $BOTTOM = "host" ]; then
  export APP_PATH=$PWD
elif [ $BOTTOM = "machine" ]; then
  export APP_PATH=${PWD/home/hosthome}
fi

docker run --rm -it \
  -e APP_PATH=${APP_PATH} \
  -v ${APP_PATH}:/myapp \
  -v /myapp/dist \
  -v /tmp \
  -v ${APP_PATH}/.bash_history:/root/.bash_history \
  --name spawebclient \
  --hostname spawebclient \
  -p 4200:4200 -p 7020:7020 -p 7357:7357 \
  danlynn/ember-cli:3.13.0-node_12.10 \
  ember serve --watcher=polling

echo
echo
